export const data = [
    {
        id: 1,
        name: "HTML",
        image: "https://img.icons8.com/color/48/000000/html-5--v1.png",
        imagebg: "https://www.searchenginejournal.com/wp-content/uploads/2020/12/9-html-tags-11-attributes-you-must-know-for-seo-5fca27dc748f4.png",
        proficiency: 7,
        description: "Frontend Development/Design",
    },
    {
        id: 2,
        name: "CSS",
        image: "https://img.icons8.com/color/48/000000/css3.png",
        imagebg: "https://i0.wp.com/css-tricks.com/wp-content/uploads/2020/01/code-block-screenshot.png?fit=1200%2C600&ssl=1",
        proficiency: 6,
        description: "Frontend Styling/Design",
    },
    {
        id: 3,
        name: "JavaScript",
        image: "https://img.icons8.com/color/48/000000/javascript--v1.png",
        imagebg: "https://assets-global.website-files.com/608a88369ffab4f5de1ed321/63f35253b68fbb93f5aedf7b_JavaScript-code.jpeg",
        proficiency: 7,
        description: "Frontend Development/ Backend Development",
    },
    {
        id: 4,
        name: "React",
        image: "https://img.icons8.com/color/48/000000/react-native.png",
        imagebg: "https://www.codingdojo.com/blog/wp-content/uploads/react.jpg",
        proficiency: 6,
        description: "Frontend Development/ Backend Development",
    },
    {
        id: 5,
        name: "C#",
        image: "https://img.icons8.com/color/48/000000/c-sharp-logo.png",
        imagebg: "https://media.istockphoto.com/id/981065334/photo/c-sharp-code-on-a-computer-screen.jpg?b=1&s=170667a&w=0&k=20&c=P7Iw9eDPTkfo7dwrQakCxUecPMKWThB44iGCyKBNwlo=",
        proficiency: 9,
        description: "Oriented Object Programming/ Unity",
    },
    {
        id: 6,
        name: "Python",
        image: "https://img.icons8.com/color/48/000000/python--v1.png",
        imagebg: "https://www.freecodecamp.org/news/content/images/2022/03/comments-python.jpg",
        proficiency: 9,
        description: "Data Science/ Machine Learning",
    },
    {
        id: 7,
        name: "AWS",
        image: "https://img.icons8.com/color/48/000000/amazon-web-services.png",
        imagebg: "https://miro.medium.com/v2/resize:fit:1400/0*rHIiRwvFINVjEqFD",
        proficiency: 7,
        description: "Amplify/API/Storage/Hosting/Authentication",
    },
    {
        id: 8,
        name: "C++",
        image: "https://img.icons8.com/color/48/000000/c-plus-plus-logo.png",
        imagebg: "https://images.pexels.com/photos/276452/pexels-photo-276452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        proficiency: 7,
        description: "Oriented Object Programming",
    },
    {
        id: 9,
        name: "C",
        image: "https://img.icons8.com/color/48/000000/c-programming.png",
        imagebg: "https://learntocodewith.me/wp-content/uploads/2022/06/C-code-1024x576.jpeg",
        proficiency: 5,
        description: "BackEnd Development/ Structured Programming",
    },
    {
        id: 10,
        name: "Elixir",
        image: "https://avatars.githubusercontent.com/u/1481354?s=280&v=4",
        imagebg: "https://remotivelabs.com/wp-content/uploads/2022/12/vinjet2.jpg",
        proficiency: 5,
        description: "General Purpose Programming Language",
    },
    {
        id: 11,
        name: "Racket",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Racket-logo.svg/768px-Racket-logo.svg.png",
        imagebg: "https://docs.racket-lang.org/style/emacs-sexp-comment.png",
        proficiency: 6,
        description: "General Purpose Programming Language",
    },
    {
        id: 12,
        name: "TypeScript",
        image: "https://img.icons8.com/color/48/000000/typescript.png",
        imagebg: "https://codecarbon.com/wp-content/uploads/2020/11/TypeScript-4.1-release.jpg",
        proficiency: 7,
        description: "Fullstack Development/ API Development",
    },
    {
        id: 13,
        name: "SQL",
        image: "https://img.icons8.com/color/48/000000/sql.png",
        imagebg: "https://www.cdotrends.com/sites/default/files/SQL.jpg",
        proficiency: 7,
        description: "Database Development",
    },
    {
        id: 14,
        name: "Tailwind",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/2048px-Tailwind_CSS_Logo.svg.png",
        imagebg: "https://res.cloudinary.com/practicaldev/image/fetch/s--ybezQPbw--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://tailwindcss.com/_next/static/media/tailwindcss-language-mode.743db867cce5edbd2a3d15d503609a45.png",
        proficiency: 8,
        description: "Frontend Styling/Design",
    },
    {
        id: 15,
        name: "React Native",
        image: "https://img.icons8.com/color/48/000000/react-native.png",
        imagebg: "https://www.freecodecamp.org/news/content/images/2022/03/photo-1619410283995-43d9134e7656.jpeg",
        proficiency: 6,
        description: "Fullstack Development",
    },
];

